#ifndef LINEARCLASSIFIER_GLOBAL_H
#define LINEARCLASSIFIER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LINEARCLASSIFIER_PLUGIN)
#  define LINEARCLASSIFIERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LINEARCLASSIFIERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LINEARCLASSIFIER_GLOBAL_H
